package cn.tedu.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2019-01-14T16:12:07.056+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://ws.tedu.cn/", name = "HelloWS")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "introduce", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.Introduce")
    @WebMethod
    @ResponseWrapper(localName = "introduceResponse", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.IntroduceResponse")
    public java.lang.String introduce(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
